- name: Crear grupos
  group:
    name: "{{ item }}"
    state: present
  loop:
    - GAlumnos
    - GProfesores

- name: Crear usuarios y asignar grupos
  user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    append: yes
    state: present
  loop:
    - { name: 'alumno', group: 'GAlumnos' }
    - { name: 'Profesor', group: 'GProfesores' }

